altinity/metrics-exporter:0.28.0: "registry.cn-shanghai.aliyuncs.com/ahoo/altinity:metrics_exporter_0.28.0"
altinity/clickhouse-operator:0.28.0: "registry.cn-shanghai.aliyuncs.com/ahoo/altinity:clickhouse_operator_0.28.0"
