# clickhouse/clickhouse-server:/^22.+/: "registry.cn-shanghai.aliyuncs.com/ahoo/clickhouse"
# clickhouse/clickhouse-server:/^23.+/: "registry.cn-shanghai.aliyuncs.com/ahoo/clickhouse"
# clickhouse/clickhouse-server:/^24.3.+/: "registry.cn-shanghai.aliyuncs.com/ahoo/clickhouse"
# clickhouse/clickhouse-server:/^24.8.+/: "registry.cn-shanghai.aliyuncs.com/ahoo/clickhouse"
clickhouse/clickhouse-server:/^24.9.+/: "registry.cn-shanghai.aliyuncs.com/ahoo/clickhouse"
clickhouse/clickhouse-server:/^24.10.+/: "registry.cn-shanghai.aliyuncs.com/ahoo/clickhouse"
clickhouse/clickhouse-server:/^24.11.+/: "registry.cn-shanghai.aliyuncs.com/ahoo/clickhouse"
clickhouse/clickhouse-server:/^24.12.+/: "registry.cn-shanghai.aliyuncs.com/ahoo/clickhouse"
# clickhouse/clickhouse-server:/^25.+/: "registry.cn-shanghai.aliyuncs.com/ahoo/clickhouse"
