clickhouse/clickhouse-server:24.1.2-alpine: "registry.cn-shanghai.aliyuncs.com/ahoo/clickhouse"
clickhouse/clickhouse-server:/^22.+/: "registry.cn-shanghai.aliyuncs.com/ahoo/clickhouse"
clickhouse/clickhouse-server:/^23.+/: "registry.cn-shanghai.aliyuncs.com/ahoo/clickhouse"
clickhouse/clickhouse-server:/^24.+/: "registry.cn-shanghai.aliyuncs.com/ahoo/clickhouse"
