# busybox
busybox:1.35: "registry.cn-shanghai.aliyuncs.com/ahoo/busybox"
busybox:1.30: "registry.cn-shanghai.aliyuncs.com/ahoo/busybox"
# curl
curlimages/curl:8.11.1: "registry.cn-shanghai.aliyuncs.com/ahoo/curl"
# signoz
groundnuty/k8s-wait-for:v2.0: "registry.cn-shanghai.aliyuncs.com/ahoo/signoz:k8s-wait-for_v2.0"
signoz/signoz-schema-migrator:0.102.0: "registry.cn-shanghai.aliyuncs.com/ahoo/signoz:signoz-schema-migrator_0.102.0"
signoz/frontend:0.48.1: "registry.cn-shanghai.aliyuncs.com/ahoo/signoz:frontend_0.48.1"
signoz/signoz-otel-collector:0.102.0: "registry.cn-shanghai.aliyuncs.com/ahoo/signoz:signoz-otel-collector_0.102.0"
signoz/alertmanager:0.23.5: "registry.cn-shanghai.aliyuncs.com/ahoo/signoz:alertmanager_0.23.5"
signoz/query-service:0.48.1: "registry.cn-shanghai.aliyuncs.com/ahoo/signoz:query-service_0.48.1"
# bitnami
bitnami/redis-cluster:7.0.5-debian-11-r9: "registry.cn-shanghai.aliyuncs.com/ahoo/bitnami:redis-cluster_7.0.5-debian-11-r9"
bitnami/kafka:3.3.1-debian-11-r1: "registry.cn-shanghai.aliyuncs.com/ahoo/bitnami:kafka_3.3.1-debian-11-r1"
bitnami/kafka:2.7.0-debian-10-r64: "registry.cn-shanghai.aliyuncs.com/ahoo/bitnami:kafka_2.7.0-debian-10-r64"
bitnami/rabbitmq:3.11.16-debian-11-r3: "registry.cn-shanghai.aliyuncs.com/ahoo/bitnami:rabbitmq_3.11.16-debian-11-r3"
bitnami/zookeeper:3.8.1-debian-11-r36: "registry.cn-shanghai.aliyuncs.com/ahoo/bitnami:zookeeper_3.8.1-debian-11-r36"
bitnami/mongodb-sharded:6.0.13-debian-11-r20: "registry.cn-shanghai.aliyuncs.com/ahoo/bitnami:mongodb-sharded_6.0.13-debian-11-r20"
bitnami/mysql:8.0.31-debian-11-r0: "registry.cn-shanghai.aliyuncs.com/ahoo/bitnami:mysql_8.0.31-debian-11-r0"
# clickhouse
clickhouse/clickhouse-server:24.1.2-alpine: "registry.cn-shanghai.aliyuncs.com/ahoo/clickhouse"
# metabase
metabase/metabase:v0.42.4: "registry.cn-shanghai.aliyuncs.com/ahoo/metabase"
metabase/metabase:v0.52.4.4: "registry.cn-shanghai.aliyuncs.com/ahoo/metabase"
# nginx
nginx:1.27.3-alpine: "registry.cn-shanghai.aliyuncs.com/ahoo/nginx"
# cosky
ahoowang/cosky-rest-api:1.3.20: "registry.cn-shanghai.aliyuncs.com/ahoo/cosky"
