# busybox
busybox:1.38: "registry.cn-shanghai.aliyuncs.com/ahoo/busybox"
busybox:1.38: "registry.cn-shanghai.aliyuncs.com/ahoo/busybox"
# curl
curlimages/curl:8.21.0: "registry.cn-shanghai.aliyuncs.com/ahoo/curl"
# signoz
groundnuty/k8s-wait-for:v2.0: "registry.cn-shanghai.aliyuncs.com/ahoo/signoz:k8s-wait-for_v2.0"
signoz/signoz-schema-migrator:v0.144.9: "registry.cn-shanghai.aliyuncs.com/ahoo/signoz:signoz-schema-migrator_v0.144.9"
signoz/frontend:1.1.0: "registry.cn-shanghai.aliyuncs.com/ahoo/signoz:frontend_1.1.0"
signoz/signoz-otel-collector:v0.144.9: "registry.cn-shanghai.aliyuncs.com/ahoo/signoz:signoz-otel-collector_v0.144.9"
signoz/alertmanager:0.23.9: "registry.cn-shanghai.aliyuncs.com/ahoo/signoz:alertmanager_0.23.9"
signoz/query-service:0.76.2: "registry.cn-shanghai.aliyuncs.com/ahoo/signoz:query-service_0.76.2"
# bitnami
bitnamilegacy/redis-cluster:7.2.4-debian-11-r9: "registry.cn-shanghai.aliyuncs.com/ahoo/bitnami:redis-cluster_7.2.4-debian-11-r9"
bitnamilegacy/kafka:3.6.1-debian-11-r1: "registry.cn-shanghai.aliyuncs.com/ahoo/bitnami:kafka_3.6.1-debian-11-r1"
# bitnamilegacy/kafka:2.7.0-debian-10-r64: "registry.cn-shanghai.aliyuncs.com/ahoo/bitnami:kafka_2.7.0-debian-10-r64"
bitnamilegacy/rabbitmq:3.12.12-debian-11-r3: "registry.cn-shanghai.aliyuncs.com/ahoo/bitnami:rabbitmq_3.12.12-debian-11-r3"
bitnamilegacy/zookeeper:3.9.0-debian-11-r36: "registry.cn-shanghai.aliyuncs.com/ahoo/bitnami:zookeeper_3.9.0-debian-11-r36"
bitnamilegacy/mongodb-sharded:7.0.5-debian-11-r20: "registry.cn-shanghai.aliyuncs.com/ahoo/bitnami:mongodb-sharded_7.0.5-debian-11-r20"
bitnamilegacy/mysql:8.3.0-debian-11-r0: "registry.cn-shanghai.aliyuncs.com/ahoo/bitnami:mysql_8.3.0-debian-11-r0"
bitnamilegacy/mysql:9.4.0-debian-12-r0: "registry.cn-shanghai.aliyuncs.com/ahoo/bitnami:mysql_9.4.0-debian-12-r0"
bitnamilegacy/wordpress:6.4.3-debian-11-r0: "registry.cn-shanghai.aliyuncs.com/ahoo/bitnami:wordpress_6.4.3-debian-11-r0"
# clickhouse
clickhouse/clickhouse-server:26.8.2-alpine: "registry.cn-shanghai.aliyuncs.com/ahoo/clickhouse"
# nginx
nginx:1.31.4-alpine: "registry.cn-shanghai.aliyuncs.com/ahoo/nginx"
