docker.elastic.co/elasticsearch/elasticsearch:8.18.1: "registry.cn-shanghai.aliyuncs.com/ahoo/elasticsearch:8.18.1"
docker.elastic.co/elasticsearch/elasticsearch:8.18.2: "registry.cn-shanghai.aliyuncs.com/ahoo/elasticsearch:8.18.2"
#docker.elastic.co/elasticsearch/elasticsearch:/^8.+/: "registry.cn-shanghai.aliyuncs.com/ahoo/elasticsearch"
