docker.elastic.co/kibana/kibana:9.5.3: "registry.cn-shanghai.aliyuncs.com/ahoo/kibana:9.5.3"
docker.elastic.co/kibana/kibana:9.5.3: "registry.cn-shanghai.aliyuncs.com/ahoo/kibana:9.5.3"
docker.elastic.co/kibana/kibana:9.5.3: "registry.cn-shanghai.aliyuncs.com/ahoo/kibana:9.5.3"
