docker.elastic.co/kibana/kibana:9.5.2: "registry.cn-shanghai.aliyuncs.com/ahoo/kibana:9.5.2"
docker.elastic.co/kibana/kibana:9.5.2: "registry.cn-shanghai.aliyuncs.com/ahoo/kibana:9.5.2"
docker.elastic.co/kibana/kibana:9.5.2: "registry.cn-shanghai.aliyuncs.com/ahoo/kibana:9.5.2"
