# metabase
metabase/metabase:v0.42.4: "registry.cn-shanghai.aliyuncs.com/ahoo/metabase"
metabase/metabase:v0.42.6: "registry.cn-shanghai.aliyuncs.com/ahoo/metabase"
metabase/metabase:v0.43.0: "registry.cn-shanghai.aliyuncs.com/ahoo/metabase"
metabase/metabase:v0.43.7.3: "registry.cn-shanghai.aliyuncs.com/ahoo/metabase"
metabase/metabase:v0.44.0: "registry.cn-shanghai.aliyuncs.com/ahoo/metabase"
metabase/metabase:v0.44.7.3: "registry.cn-shanghai.aliyuncs.com/ahoo/metabase"
metabase/metabase:v0.45.0: "registry.cn-shanghai.aliyuncs.com/ahoo/metabase"
metabase/metabase:v0.45.4.3: "registry.cn-shanghai.aliyuncs.com/ahoo/metabase"
metabase/metabase:v0.46.0: "registry.cn-shanghai.aliyuncs.com/ahoo/metabase"
metabase/metabase:v0.46.8: "registry.cn-shanghai.aliyuncs.com/ahoo/metabase"
metabase/metabase:v0.47.0: "registry.cn-shanghai.aliyuncs.com/ahoo/metabase"
metabase/metabase:v0.47.13: "registry.cn-shanghai.aliyuncs.com/ahoo/metabase"
metabase/metabase:v0.48.0: "registry.cn-shanghai.aliyuncs.com/ahoo/metabase"
metabase/metabase:v0.48.13: "registry.cn-shanghai.aliyuncs.com/ahoo/metabase"
metabase/metabase:v0.49.0: "registry.cn-shanghai.aliyuncs.com/ahoo/metabase"
metabase/metabase:v0.49.25.2: "registry.cn-shanghai.aliyuncs.com/ahoo/metabase"
metabase/metabase:v0.50.0-RC2: "registry.cn-shanghai.aliyuncs.com/ahoo/metabase"
metabase/metabase:v0.50.36: "registry.cn-shanghai.aliyuncs.com/ahoo/metabase"
metabase/metabase:v0.51.0.10-beta: "registry.cn-shanghai.aliyuncs.com/ahoo/metabase"
metabase/metabase:v0.51.14: "registry.cn-shanghai.aliyuncs.com/ahoo/metabase"
metabase/metabase:v0.52.0.5-beta: "registry.cn-shanghai.aliyuncs.com/ahoo/metabase"
metabase/metabase:v0.52.4.4: "registry.cn-shanghai.aliyuncs.com/ahoo/metabase"
metabase/metabase:v0.52.17.1: "registry.cn-shanghai.aliyuncs.com/ahoo/metabase"
metabase/metabase:v0.53.0.4-beta: "registry.cn-shanghai.aliyuncs.com/ahoo/metabase"
metabase/metabase:v0.53.18.1: "registry.cn-shanghai.aliyuncs.com/ahoo/metabase"
metabase/metabase:v0.54.0.3-beta: "registry.cn-shanghai.aliyuncs.com/ahoo/metabase"
metabase/metabase:v0.54.23: "registry.cn-shanghai.aliyuncs.com/ahoo/metabase"
metabase/metabase:v0.55.0.2-beta: "registry.cn-shanghai.aliyuncs.com/ahoo/metabase"
metabase/metabase:v0.55.23: "registry.cn-shanghai.aliyuncs.com/ahoo/metabase"
metabase/metabase:v0.56.0.3-beta: "registry.cn-shanghai.aliyuncs.com/ahoo/metabase"
metabase/metabase:v0.56.23: "registry.cn-shanghai.aliyuncs.com/ahoo/metabase"
metabase/metabase:v0.57.0-beta: "registry.cn-shanghai.aliyuncs.com/ahoo/metabase"
metabase/metabase:v0.57.17: "registry.cn-shanghai.aliyuncs.com/ahoo/metabase"
metabase/metabase:v0.58.0.10-beta: "registry.cn-shanghai.aliyuncs.com/ahoo/metabase"
metabase/metabase:v0.58.13: "registry.cn-shanghai.aliyuncs.com/ahoo/metabase"
metabase/metabase:v0.59.0.7-beta: "registry.cn-shanghai.aliyuncs.com/ahoo/metabase"
metabase/metabase:v0.59.7.1: "registry.cn-shanghai.aliyuncs.com/ahoo/metabase"
metabase/metabase:v0.60.0.8-beta: "registry.cn-shanghai.aliyuncs.com/ahoo/metabase"
metabase/metabase:v0.60.1.1: "registry.cn-shanghai.aliyuncs.com/ahoo/metabase"
metabase/metabase:v0.60.1.4: "registry.cn-shanghai.aliyuncs.com/ahoo/metabase"
metabase/metabase:v0.60.2.3: "registry.cn-shanghai.aliyuncs.com/ahoo/metabase"
