name: Sync ElasticSearch Image
on:
  workflow_dispatch:
jobs:
  SyncElasticSearchImage:
    name: Sync ElasticSearch Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Sync ElasticSearch Image
        uses: hhyasdf/image-sync-action@v1.1
        env:
          ALIYUN_CR_USERNAME: ${{ secrets.ALIYUN_CR_USERNAME }}
          ALIYUN_CR_PASSWORD: ${{ secrets.ALIYUN_CR_PASSWORD }}
        with:
          auth_file: ./config/auth.yaml
          images_file: ./config/elasticsearch-images.yaml
          version: latest